type: Forecast
name: MTGNN
gcn_true: true
buildA_true: true
load_static_feature: false
cl: true

gcn_depth: 2
num_nodes: 207
dropout: 0.3
subgraph_size: 20
node_dim: 40
dilation_exponential: 1

conv_channels: 32
residual_channels: 32
skip_channels: 64
end_channels: 128

in_dim: 2
seq_in_len: 12
seq_out_len: 12

layers: 3
batch_size: 64
learning_rate: 0.001
weight_decay: 0.0001
clip: 5
step_size1: 2500
step_size2: 100
